# Loop infinito‚ôæ

Em Python, um loop infinito ocorre quando  um la√ßo (e.g. 'while' ou 'for') continua a executar indefinidamente, sem nunca encontrar uma condi√ß√£o que o fa√ßa parar. Isso pode acontecer, por exemplo, se a condi√ß√£o de t√©rmino do la√ßo nunca se tornar falsa ou se houver um erro na l√≥gica do la√ßo. 

## üìåExemplo de Loop Infinito com while
![Captura de tela 2024-08-10 170459](https://github.com/user-attachments/assets/64045260-3d5e-49a7-b0de-8958db31d857)

![image](https://github.com/user-attachments/assets/35b861eb-a2d9-4442-97b9-71da089206e2)

No exemplo acima, o valor de contador nunca √© incrementado, o que significa que a condi√ß√£o contador < 5 permanecer√° verdadeira para sempreüò±, fazendo com que o la√ßo _while_ nunca termine.

### üö®Loops infinitos podem causar problemas, como travamentos de programa ou consumo excessivo de recursos do sistemaüö®

## üÜò Como Evitar Loops Infinitos
| Estrat√©gias    | Detalhamento |
| ------ | ---------|
üß© **Certifique-se de que a condi√ß√£o se torne falsa**| Ao usar _while_, garanta que a condi√ß√£o de t√©rmino seja atingida em algum momento. Isso geralmente envolve modifica√ß√£o de vari√°veis dentro do loop para que a condi√ß√£o seja satisfeita. Issue#2|
üß© **Use _break_ para sair do loop** | O comando _break_ pode ser usado para sair de um loop antecipadamente, independentemente da condi√ß√£o. Isso √© √∫til se voc√™ estiver esperando uma condi√ß√£o espec√≠fica que n√£o seja facilmente expressa na pr√≥pria condi√ß√£o do _while_. Issue#3 |
üß© **Limite itera√ß√µes com contadores** | Em alguns casos, √© √∫til incluir um contador que limite o n√∫mero m√°ximo de itera√ß√µes, mesmo que a condi√ß√£o principal do loop n√£o tenha sido atendida. #Issue#4|
üß© **Evite depend√™ncias externas descontroladas** | Se o loop depende de fatores externos, como a leitura de dados de um arquivo ou uma entrada do usu√°rio, certifique-se de que h√° uma condi√ß√£o de escape clara.




